name: X-Prison
version: 1.13.1
main: dev.drawethree.xprison.XPrison
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
authors: [ Drawethree, WildInterloper, never2nv ]
api-version: 1.21
load: POSTWORLD
website: www.drawethree.dev
